server:
  port: 8081

spring:
  application:
    name: pay

  datasource:
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/paydemo?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
